INSERT INTO public."Nickname" VALUES
(gen_random_uuid(), 'сияющий лаготворитель'),
(gen_random_uuid(), 'лучезарный хрометей'),
(gen_random_uuid(), 'полубокий однобок'),
(gen_random_uuid(), 'пивви-бух'),
(gen_random_uuid(), 'незабитый мяч'),
(gen_random_uuid(), 'лоту кеды'),
(gen_random_uuid(), 'поменявшийся каток лотку'),
(gen_random_uuid(), 'лiдскае вкусное'),
(gen_random_uuid(), 'ыизнерадостный душевноздоровый'),
(gen_random_uuid(), 'карликовый дракон'),
(gen_random_uuid(), 'осадный президент'),
(gen_random_uuid(), 'преславутый пират'),
(gen_random_uuid(), 'карликовый мяч'),
(gen_random_uuid(), 'ворчливый Перфоратор'),
(gen_random_uuid(), 'гондон'),
(gen_random_uuid(), 'педрила тупорылый'),
(gen_random_uuid(), 'усатый'),
(gen_random_uuid(), 'дворовая скачелька'),
(gen_random_uuid(), 'вышеупомянутый ниже-названный'),
(gen_random_uuid(), 'властелин-пластилин'),
(gen_random_uuid(), 'никто'),
(gen_random_uuid(), 'бибка'),
(gen_random_uuid(), 'бобка'),
(gen_random_uuid(), 'Биба'),
(gen_random_uuid(), 'Боба'),
(gen_random_uuid(), 'Лупа'),
(gen_random_uuid(), 'Пупа '),
(gen_random_uuid(), 'Залупа'),
(gen_random_uuid(), 'и Бибка и Бобка'),
(gen_random_uuid(), 'жопа'),
(gen_random_uuid(), 'щербатый'),
(gen_random_uuid(), 'торч'),
(gen_random_uuid(), 'членодевка'),
(gen_random_uuid(), 'вверх вниз и обратно'),
(gen_random_uuid(), 'особо одаренный'),
(gen_random_uuid(), 'индивидуум'),
(gen_random_uuid(), 'гений'),
(gen_random_uuid(), 'iq 20'),
(gen_random_uuid(), 'ничесси'),
(gen_random_uuid(), 'Хахладыж'),
(gen_random_uuid(), 'Никита прости его Г-споди...'),
(gen_random_uuid(), 'ПЕРЕПИЗДРЮЧЕННЫЙ ГОЛШТИНСКИЙ ПИЗДОДЕРЖЕЦ'),
(gen_random_uuid(), 'ХУЯЛЫГА ПИЗДОДРАЧЕНАЯ'),
(gen_random_uuid(), 'смердящий скунс'),
(gen_random_uuid(), 'шкила'),
(gen_random_uuid(), 'Z'),
(gen_random_uuid(), 'зубной состав'),
(gen_random_uuid(), 'оргазм насвая'),
(gen_random_uuid(), 'талантливый бесталантище'),
(gen_random_uuid(), 'иситчик на хую виситчик'),
(gen_random_uuid(), 'говно залупа пенис хер'),
(gen_random_uuid(), 'краткий утeнок '),
(gen_random_uuid(), 'подзалупный творожок'),
(gen_random_uuid(), 'удав в кулаке'),
(gen_random_uuid(), 'одноглазый змей'),
(gen_random_uuid(), 'зверь с тремя ликами'),
(gen_random_uuid(), 'EVA 00'),
(gen_random_uuid(), 'EVA 01'),
(gen_random_uuid(), 'EVA 02'),
(gen_random_uuid(), 'ded'),
(gen_random_uuid(), 'желчестрадающий ангел'),
(gen_random_uuid(), 'убуб'),
(gen_random_uuid(), 'вагнеровец с кувалдой'),
(gen_random_uuid(), 'установленная винда'),
(gen_random_uuid(), 'генетическая помарка '),
(gen_random_uuid(), 'дристающий ангел'),
(gen_random_uuid(), 'взрыв кабачка в коляске с поносом'),
(gen_random_uuid(), 'синдромирующий живым труп'),
(gen_random_uuid(), 'демон из зада'),
(gen_random_uuid(), 'расщепленный неделимый'),
(gen_random_uuid(), 'монолитный стихотворец'),
(gen_random_uuid(), 'клаксующий такосон'),
(gen_random_uuid(), 'колющийся ёж'),
(gen_random_uuid(), 'полоска на еноте'),
(gen_random_uuid(), 'число авангарда'),
(gen_random_uuid(), 'блевотина распутного бомжа'),
(gen_random_uuid(), 'веревка без мыла'),
(gen_random_uuid(), 'табуретка с четырмя людьми на ножках'),
(gen_random_uuid(), 'Виталя'),
(gen_random_uuid(), 'абсолютный Никита '),
(gen_random_uuid(), '3D: дебил дурак и долбаеб '),
(gen_random_uuid(), 'рассчитаный однораз'),
(gen_random_uuid(), 'заяц из пениса'),
(gen_random_uuid(), 'вибратор'),
(gen_random_uuid(), 'растущий гемоглабин'),
(gen_random_uuid(), 'зубная вош '),
(gen_random_uuid(), 'пубертатная язва'),
(gen_random_uuid(), 'педрила-гомодрила'),
(gen_random_uuid(), 'ганзолька'),
(gen_random_uuid(), 'волосатый боребух'),
(gen_random_uuid(), 'отчисленец'),
(gen_random_uuid(), 'неуродимая медицина'),
(gen_random_uuid(), 'Алиноподобное сцущество'),
(gen_random_uuid(), 'сектор "ДРИСЬ"'),
(gen_random_uuid(), 'распространитель тронов'),
(gen_random_uuid(), 'коричневый алабай'),
(gen_random_uuid(), 'жмышевский бурят'),
(gen_random_uuid(), 'чередование знаков'),
(gen_random_uuid(), 'драгоценный щебень'),
(gen_random_uuid(), 'овощной опус '),
(gen_random_uuid(), 'голубой слон'),
(gen_random_uuid(), 'зеленый слоник'),
(gen_random_uuid(), 'черствый Олег'),
(gen_random_uuid(), 'червивая матка'),
(gen_random_uuid(), 'портированный DOOM'),
(gen_random_uuid(), 'Зеленский'),
(gen_random_uuid(), 'сгоревший ареал'),
(gen_random_uuid(), 'страдающий дед'),
(gen_random_uuid(), 'скаут'),
(gen_random_uuid(), 'пиро '),
(gen_random_uuid(), 'солда'),
(gen_random_uuid(), 'демоман'),
(gen_random_uuid(), 'хеви'),
(gen_random_uuid(), 'инженер'),
(gen_random_uuid(), 'врач'),
(gen_random_uuid(), 'снайпер'),
(gen_random_uuid(), 'шпион'),
(gen_random_uuid(), 'негр'),
(gen_random_uuid(), 'раб на плантации'),
(gen_random_uuid(), 'разбитое сердце'),
(gen_random_uuid(), 'жопотрах'),
(gen_random_uuid(), 'членосос'),
(gen_random_uuid(), 'хуец'),
(gen_random_uuid(), 'раздолбленный анус'),
(gen_random_uuid(), 'сглыпа'),
(gen_random_uuid(), 'Ярик'),
(gen_random_uuid(), 'протекший бочок'),
(gen_random_uuid(), 'тактильный человек'),
(gen_random_uuid(), 'Кайл'),
(gen_random_uuid(), 'Кенни'),
(gen_random_uuid(), 'Стен'),
(gen_random_uuid(), 'Картман'),
(gen_random_uuid(), 'Вовка'),
(gen_random_uuid(), 'круглый идиот'),
(gen_random_uuid(), 'лямбда выражение'),
(gen_random_uuid(), 'агонизирующий предлог'),
(gen_random_uuid(), 'зубодробильный кусок'),
(gen_random_uuid(), 'хозяйственное состояние'),
(gen_random_uuid(), 'обделенный всем'),
(gen_random_uuid(), 'опухоль в виде мозга'),
(gen_random_uuid(), 'спам на почте'),
(gen_random_uuid(), 'разделитель зада пополам'),
(gen_random_uuid(), 'небинарный бинарный'),
(gen_random_uuid(), 'трапик'),
(gen_random_uuid(), 'сломанная газель'),
(gen_random_uuid(), 'сортирный крикун'),
(gen_random_uuid(), 'друг бактерий'),
(gen_random_uuid(), 'злодей британец'),
(gen_random_uuid(), 'недопонятый гений'),
(gen_random_uuid(), 'ге(ни)й'),
(gen_random_uuid(), 'бронхиальный СПИД'),
(gen_random_uuid(), 'папка Люка'),
(gen_random_uuid(), 'попугай Кеша'),
(gen_random_uuid(), 'кiшка'),
(gen_random_uuid(), 'коловритный модник'),
(gen_random_uuid(), 'водный курсач'),
(gen_random_uuid(), 'член членства многочленов'),
(gen_random_uuid(), 'ты просто ты'),
(gen_random_uuid(), 'всенемогущее могущество'),
(gen_random_uuid(), 'всемогущее немогущество'),
(gen_random_uuid(), 'глина'),
(gen_random_uuid(), 'ножной амбидекстер'),
(gen_random_uuid(), 'трахтор'),
(gen_random_uuid(), 'сексоратор'),
(gen_random_uuid(), 'анальный дробитель'),
(gen_random_uuid(), 'анальный грабитель'),
(gen_random_uuid(), 'калловая масса непризнанного деда'),
(gen_random_uuid(), 'барманьяк'),
(gen_random_uuid(), 'скоковпитывалка'),
(gen_random_uuid(), 'болотный жабомет'),
(gen_random_uuid(), 'чернобыльский болтометатель'),
(gen_random_uuid(), 'псевдонегр'),
(gen_random_uuid(), 'Парамаунт Дикчерс'),
(gen_random_uuid(), 'титановый хер'),
(gen_random_uuid(), 'крылечко с колечка'),
(gen_random_uuid(), 'анальный уничтожитель'),
(gen_random_uuid(), 'смотритель прямой кишки'),
(gen_random_uuid(), 'глиномес'),
(gen_random_uuid(), 'многострадалец'),
(gen_random_uuid(), 'смертный таракан'),
(gen_random_uuid(), 'главграч'),
(gen_random_uuid(), 'Неизвестный Исполнитель'),
(gen_random_uuid(), '1234567890'),
(gen_random_uuid(), 'первый в списке пидоров'),
(gen_random_uuid(), 'первопроходец уретры'),
(gen_random_uuid(), 'уретральный глист'),
(gen_random_uuid(), 'яйцо карлика'),
(gen_random_uuid(), 'игровая простата'),
(gen_random_uuid(), 'игривая девочка'),
(gen_random_uuid(), 'отбитый и израненный'),
(gen_random_uuid(), 'отпятное сцыкло'),
(gen_random_uuid(), 'незаписанный файл'),
(gen_random_uuid(), 'питонист'),
(gen_random_uuid(), 'разбитый и недотраханный'),
(gen_random_uuid(), 'главный злодей'),
(gen_random_uuid(), 'зубастый немой'),
(gen_random_uuid(), 'переломленный пополам разбитка'),
(gen_random_uuid(), 'бургулированный артемид'),
(gen_random_uuid(), 'гельминтозозависимый недосып'),
(gen_random_uuid(), 'ургально-ванильный ираник');